from flask import ( Flask, render_template, request, redirect, url_for, session, jsonify, send_from_directory, abort ) from flask_socketio import SocketIO, emit, join_room from flask_sqlalchemy import SQLAlchemy from werkzeug.utils import secure_filename from datetime import datetime from PIL import Image import bcrypt import os import uuid
app = Flask(name) app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'change-me-please-12345') app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///messenger.db' app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False app.config['MAX_CONTENT_LENGTH'] = 25 * 1024 * 1024
UPLOAD_DIR = os.path.join(os.path.dirname(file), 'uploads') AVATAR_DIR = os.path.join(UPLOAD_DIR, 'avatars') FILE_DIR = os.path.join(UPLOAD_DIR, 'files') VOICE_DIR = os.path.join(UPLOAD_DIR, 'voice') for d in (AVATAR_DIR, FILE_DIR, VOICE_DIR): os.makedirs(d, exist_ok=True)
ALLOWED_IMAGES = {'png', 'jpg', 'jpeg', 'gif', 'webp'} ALLOWED_FILES = {'pdf', 'txt', 'doc', 'docx', 'zip', 'mp3', 'mp4', 'png', 'jpg', 'jpeg', 'gif'}
db = SQLAlchemy(app) socketio = SocketIO(app, cors_allowed_origins="*", max_http_buffer_size=25_000_000, async_mode='eventlet')
============ МОДЕЛІ ============
class User(db.Model): id = db.Column(db.Integer, primary_key=True) username = db.Column(db.String(50), unique=True, nullable=False) password_hash = db.Column(db.String(200), nullable=False) avatar = db.Column(db.String(200), default=None) bio = db.Column(db.String(200), default='') public_key = db.Column(db.Text, default=None) last_seen = db.Column(db.DateTime, default=datetime.utcnow) created_at = db.Column(db.DateTime, default=datetime.utcnow)
class Chat(db.Model): id = db.Column(db.Integer, primary_key=True) name = db.Column(db.String(100), default=None) is_group = db.Column(db.Boolean, default=False) avatar = db.Column(db.String(200), default=None) created_by = db.Column(db.Integer, db.ForeignKey('user.id')) created_at = db.Column(db.DateTime, default=datetime.utcnow) members = db.relationship('ChatMember', backref='chat', cascade='all, delete-orphan')
class ChatMember(db.Model): id = db.Column(db.Integer, primary_key=True) chat_id = db.Column(db.Integer, db.ForeignKey('chat.id'), nullable=False) user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False) joined_at = db.Column(db.DateTime, default=datetime.utcnow) is_admin = db.Column(db.Boolean, default=False) user = db.relationship('User') table_args = (db.UniqueConstraint('chat_id', 'user_id'),)
class Message(db.Model): id = db.Column(db.Integer, primary_key=True) chat_id = db.Column(db.Integer, db.ForeignKey('chat.id'), nullable=False) sender_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False) text = db.Column(db.Text, default='') message_type = db.Column(db.String(20), default='text') file_path = db.Column(db.String(300), default=None) file_name = db.Column(db.String(300), default=None) file_size = db.Column(db.Integer, default=0) duration = db.Column(db.Float, default=0) reply_to = db.Column(db.Integer, db.ForeignKey('message.id'), default=None) timestamp = db.Column(db.DateTime, default=datetime.utcnow) is_read = db.Column(db.Boolean, default=False) edited = db.Column(db.Boolean, default=False) sender = db.relationship('User', foreign_keys=[sender_id])
class Reaction(db.Model): id = db.Column(db.Integer, primary_key=True) message_id = db.Column(db.Integer, db.ForeignKey('message.id'), nullable=False) user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False) emoji = db.Column(db.String(10), nullable=False) table_args = (db.UniqueConstraint('message_id', 'user_id', 'emoji'),)
============ ДОПОМІЖНЕ ============
def hash_password(password): return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
def check_password(password, hashed): return bcrypt.checkpw(password.encode(), hashed.encode())
def get_or_create_private_chat(user_a, user_b): subq = db.session.query(ChatMember.chat_id).filter( ChatMember.user_id.in_([user_a, user_b]) ).group_by(ChatMember.chat_id).having(db.func.count(ChatMember.user_id) == 2).subquery() chat = Chat.query.filter(Chat.is_group == False, Chat.id.in_(db.session.query(subq))).first() if not chat: chat = Chat(is_group=False, created_by=user_a) db.session.add(chat) db.session.flush() db.session.add_all([ ChatMember(chat_id=chat.id, user_id=user_a), ChatMember(chat_id=chat.id, user_id=user_b), ]) db.session.commit() return chat
def chat_to_dict(chat, current_user_id): members = [{ 'id': m.user.id, 'username': m.user.username, 'avatar': m.user.avatar, } for m in chat.members] if chat.is_group: title, avatar = chat.name or 'Група', chat.avatar else: other = next((m for m in members if m['id'] != current_user_id), None) title = other['username'] if other else 'Чат' avatar = other['avatar'] if other else None last_msg = Message.query.filter_by(chat_id=chat.id).order_by(Message.timestamp.desc()).first() return { 'id': chat.id, 'is_group': chat.is_group, 'title': title, 'avatar': avatar, 'members': members, 'last_message': { 'text': last_msg.text if last_msg else '', 'timestamp': last_msg.timestamp.isoformat() if last_msg else None, } if last_msg else None, }
def serialize_msg(m): return { 'id': m.id, 'chat_id': m.chat_id, 'sender_id': m.sender_id, 'sender_name': m.sender.username, 'text': m.text, 'type': m.message_type, 'file_path': m.file_path, 'file_name': m.file_name, 'file_size': m.file_size, 'duration': m.duration, 'reply_to': m.reply_to, 'timestamp': m.timestamp.strftime('%H:%M'), 'reactions': [], }
def allowed_file(filename, allowed): return '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed
============ МАРШРУТИ ============
@app.route('/') def index(): return redirect(url_for('chat') if 'user_id' in session else url_for('login'))
@app.route('/register', methods=['GET', 'POST']) def register(): if request.method == 'POST': username = request.form.get('username', '').strip() password = request.form.get('password', '') if not username or len(password) < 4: return render_template('index.html', error='Логін і пароль (мін. 4) обовʼязкові', mode='register') if User.query.filter_by(username=username).first(): return render_template('index.html', error='Користувач вже існує', mode='register') user = User(username=username, password_hash=hash_password(password)) db.session.add(user) db.session.commit() session['user_id'] = user.id session['username'] = user.username return redirect(url_for('chat')) return render_template('index.html', mode='register')
@app.route('/login', methods=['GET', 'POST']) def login(): if request.method == 'POST': username = request.form.get('username', '').strip() password = request.form.get('password', '') user = User.query.filter_by(username=username).first() if user and check_password(password, user.password_hash): session['user_id'] = user.id session['username'] = user.username return redirect(url_for('chat')) return render_template('index.html', error='Невірний логін або пароль', mode='login') return render_template('index.html', mode='login')
@app.route('/logout') def logout(): session.clear() return redirect(url_for('login'))
@app.route('/chat') def chat(): if 'user_id' not in session: return redirect(url_for('login')) user = User.query.get(session['user_id']) return render_template('chat.html', username=user.username, user_id=user.id, avatar=user.avatar or '', bio=user.bio or '')
@app.route('/api/me') def api_me(): if 'user_id' not in session: return jsonify({'error': 'unauthorized'}), 401 u = User.query.get(session['user_id']) return jsonify({'id': u.id, 'username': u.username, 'avatar': u.avatar, 'bio': u.bio})
@app.route('/api/users') def api_users(): if 'user_id' not in session: return jsonify({'error': 'unauthorized'}), 401 me = session['user_id'] users = User.query.filter(User.id != me).all() return jsonify([{ 'id': u.id, 'username': u.username, 'avatar': u.avatar, 'bio': u.bio, } for u in users])